### Base URL
@base_url=http://localhost:3000
@email=test1@test.com
@eventId=federa

###
# @name createUser
POST {{base_url}}/create-users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2lkZW50aXR5dG9vbGtpdC5nb29nbGVhcGlzLmNvbS9nb29nbGUuaWRlbnRpdHkuaWRlbnRpdHl0b29sa2l0LnYxLklkZW50aXR5VG9vbGtpdCIsImlhdCI6MTcyMzQxNDU4NCwiZXhwIjoxNzIzNDE4MTg0LCJpc3MiOiJmaXJlYmFzZS1hZG1pbnNkay0zbmZvekBmZWRlcmEtYXBpLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic3ViIjoiZmlyZWJhc2UtYWRtaW5zZGstM25mb3pAZmVkZXJhLWFwaS5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsInVpZCI6IjlkS2pSa01Fc0poVFpsYms4anFWeGV4RnltejIifQ.pbYxb1czH52DgVwtNCTMn2f78C7DNqfqpL-aHwXnYBAP0_pMZ1RtTbl4lQpLUvEHEu09G8VuI-cDg6RtMQ2l90WDVZqTXI1SnA4RIU32bYelmwBXVjtd3tvk82ZtLScEdd-tb9mDjpwTecMRhkHDapPHHeuSGHdA3yMnsNpYEuvADUc9CZnV9QMtsR5FEQ3xzasoiJLBNcJ3mg1LewHlkl4INZAOvDBIDThOLYdzWv1blCYAiLorz8e6YBVtf8BuD0iQmssjgN0HUKu6WTlZV3UvLRvURSQH-8aHv0MZWVWY22hqv_qIIp9BUpDQdfjuahUbhiHBrJtBPOPdET7XLg

{
  "userType": "client",
  "name": "Ariela Stefanini ",
  "church": "IPI Alpinópolis",
  "pastor": "Vitor",
  "ddd": "35",
  "cellphone": "99818536351",
  "gender": "male",
  "cep": "37.940-000",
  "cpf": "01885159895",
  "data_nasc":"17/03/1993",
  "idade": 18,
  "responsavel": "Paulo",
  "documento_responsavel": "05904651805",
  "ddd_responsavel": "35",
  "cellphone_responsavel": "999095569",
  "address": "Rua Antonio Divino de Morais",
  "complemento": "",
  "cidade": "Alpinopolis",
  "estado": "MG",
  "alergia": "Não",
  "medicamento":"Não",
  "info_add": "Nao"
}

###
# @name getUserById
GET {{base_url}}/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2lkZW50aXR5dG9vbGtpdC5nb29nbGVhcGlzLmNvbS9nb29nbGUuaWRlbnRpdHkuaWRlbnRpdHl0b29sa2l0LnYxLklkZW50aXR5VG9vbGtpdCIsImlhdCI6MTcyMzQxNDU4NCwiZXhwIjoxNzIzNDE4MTg0LCJpc3MiOiJmaXJlYmFzZS1hZG1pbnNkay0zbmZvekBmZWRlcmEtYXBpLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic3ViIjoiZmlyZWJhc2UtYWRtaW5zZGstM25mb3pAZmVkZXJhLWFwaS5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsInVpZCI6IjlkS2pSa01Fc0poVFpsYms4anFWeGV4RnltejIifQ.pbYxb1czH52DgVwtNCTMn2f78C7DNqfqpL-aHwXnYBAP0_pMZ1RtTbl4lQpLUvEHEu09G8VuI-cDg6RtMQ2l90WDVZqTXI1SnA4RIU32bYelmwBXVjtd3tvk82ZtLScEdd-tb9mDjpwTecMRhkHDapPHHeuSGHdA3yMnsNpYEuvADUc9CZnV9QMtsR5FEQ3xzasoiJLBNcJ3mg1LewHlkl4INZAOvDBIDThOLYdzWv1blCYAiLorz8e6YBVtf8BuD0iQmssjgN0HUKu6WTlZV3UvLRvURSQH-8aHv0MZWVWY22hqv_qIIp9BUpDQdfjuahUbhiHBrJtBPOPdET7XLg


### Chamada POST login
# @name login
POST {{base_url}}/auth/login
Content-Type: application/json

{
    "email": "ariela.stefanini@sou.unifal-mg.edu.br"
}

###
@token = {{login.response.body.token}}

###
# @name ListUser
GET {{base_url}}/users/list-users
Content-Type: application/json
Authorization: Bearer {{token}}


###
# @name updateUser
PATCH  {{base_url}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Updated Name",
    "email": "ariela.stefanini@sou.unifal-mg.edu.br"
}

###
# @name deleteUser
DELETE {{base_url}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

###
# @name listUsers
GET {{base_url}}/users