GET http://localhost:3000/events

###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "New Event12",
    "description": "Federa2024",
    "date": "2024-06-22T00:00:00Z",
    "price": 30000
}
###

@eventId = {{ createEvent.response.body.id }}


###
# @name createUser
POST http://localhost:3000/users
Content-Type: application/json

{
  "userId": "ariela",
  "email": "ariela@gmail.com",
  "userType": "CLIENT",
  "gender": "female"
}
###

@userId = {{ createUser.response.body.id }}

###
# @name getUserById
GET http://localhost:3000/users/{{userId}}

###
# @name updateUser
PATCH  http://localhost:3000/users/{{userId}}
Content-Type: application/json

{
    "name": "Updated Name",
    "email": "updated.email@example.com"
}

###
POST http://localhost:3000/events/{{eventId}}/reserve-spot
Content-Type: application/json

{
  "ticket_kind": "full",
  "email": "user@example.com",
  "userType": "CLIENT",
  "gender": "MALE"
}
