###
# @name createUser
POST http://localhost:3000/users
Content-Type: application/json

{
  "userId": "user123",
  "email": "user11@example.com",
  "userType": "CLIENT",
  "gender": "MALE"
}
###

@userId = {{ createUser.response.body.id }}

###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
      "name": "federa",
      "date": "2024-01-01",
      "location": "betel",
      "eventType": "general",
      "maxClientMale": "" ,
      "maxClientFemale": "",
      "maxStaffMale": "",
      "maxStaffFemale": "",
      "maxGeneralSpots": "300",
      "startDate": "2024-08-01T00:00:00Z",
      "endDate": "2024-08-01T23:59:59Z"
}

###

@eventId = {{ createEvent.response.body.id }}

###
# @name makeReservation
POST http://localhost:3000/events/{{eventId}}/reserve-spot
Content-Type: application/json

{
  "spots": ["Spot A1"],
  "ticket_kind": "full",
  "email": "user11@example.com",
  "userType": "CLIENT",
  "gender": "MALE",
  "userId": "{{userId}}"
}

###

@spotId = {{ makeReservation.response.body.id }}

### Get reservations for a specific user
# @name getReservationByUser
GET http://localhost:3000/users/{{userId}}/reservations

### Get reservations for a specific event
# @name getReservationByEvents
GET http://localhost:3000/events/{{eventId}}/reservations


### Get installments
# @name getInstallments
GET http://localhost:3000/events/{{eventId}}/installments



### Verificar Status de Inscrição para um Evento
# @name TIME inscicao
GET http://localhost:3000/events/{{eventId}}/registration-status




###
# @name getUserById
GET http://localhost:3000/users/{{userId}}
###
# @name updateUser
PATCH  http://localhost:3000/users/{{userId}}
Content-Type: application/json

{
    "name": "Updated Name",
    "email": "updated.email@example.com"
}
###
# @name deleteUser
DELETE http://localhost:3000/users/{{userId}}




###
GET http://localhost:3000/events

###
GET http://localhost:3000/events/{{eventId}}

###
PUT http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
    "name": "UPDATE",
    "description": "Federa2024",
    "date": "2024-06-22T00:00:00Z",
    "price": 30000
}

###
DELETE http://localhost:3000/events/{{eventId}}


# ###  
# # @name createSpot
# POST http://localhost:3000/events/{{eventId}}/spots
# Content-Type: application/json

# {
#     "name": "comprando um vag1a",
#     "type": "user_spot"
# }

# ###
# GET http://localhost:3000/events/{{eventId}}/spots

# ###

# @spotName = {{ createSpot.response.body.name }}
