### Base URL
@base_url=http://localhost:3000
@eventId=federa1
@email=test@test.com
@token="${env:TOKEN}"

###
# @name createCupom/updateCupom
POST http://localhost:3000/cupons/{{eventId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "CUPOM2",
  "discount": 0.7
}

###
# @name listCupons
GET http://localhost:3000/cupons/{{eventId}}
Content-Type: application/json
Authorization: Bearer {{token}}

###
# @name deleteCupom
DELETE http://localhost:3000/cupons/{{eventId}}?name=CUPOM
Content-Type: application/json
Authorization: Bearer {{token}}
