### Base URL
@base_url=http://localhost:3000
@email = test@test.com
@eventId=federa2025
@token=" "

###
# @name createCupom/updateCupom
POST {{base_url}}/cupons/{{eventId}}
Content-Type: application/json
Authorization: Bearer  

{
  "name": "CUPOM32",
  "discount": 0.72
}

###
# @name listCupons
GET {{base_url}}/cupons/{{eventId}}
Content-Type: application/json
Authorization: Bearer  

###
# @name deleteCupom
DELETE {{base_url}}/cupons/{{eventId}}?name=CUPOM32
Content-Type: application/json
Authorization: Bearer 
