### Base URL
@base_url=http://127.0.0.1:5001/federa-api/us-central1/api
@email=test1@test.com
@eventId=federa
@token="${env:TOKEN}"

###
# @name createUser
POST {{base_url}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userType": "client",
  "name": "Ariela Stefanini ",
  "church": "IPI Alpinópolis",
  "pastor": "Vitor",
  "ddd": "35",
  "cellphone": "99818536351",
  "gender": "male",
  "cep": "37.940-000",
  "cpf": "91",
  "data_nasc":"17/03/1993",
  "idade": 18,
  "responsavel": "Paulo",
  "documento_responsavel": "05904651805",
  "ddd_responsavel": "35",
  "cellphone_responsavel": "999095569",
  "address": "Rua Antonio Divino de Morais",
  "complemento": "",
  "cidade": "Alpinopolis",
  "estado": "MG",
  "alergia": "Não",
  "medicamento":"Não",
  "info_add": "Nao"
}

###
# @name getUserById
GET {{base_url}}/users
Content-Type: application/json
Authorization: Bearer {{token}}


###
# @name ListUser
GET {{base_url}}/users/list-users
Content-Type: application/json
Authorization: Bearer {{token}}

###
# @name updateUser
PATCH  {{base_url}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Updated Name",
    "email": "costumer@costumer.br"
}

###
# @name deleteUser
DELETE {{base_url}}/users
Content-Type: application/json
Authorization: Bearer {{token}}
