### Base URL
@base_url=https://us-central1-federa-api.cloudfunctions.net/api
@eventId=federa1
@email=test@test.com
@token=

###
# @name createEvent
POST {{base_url}}/events
Content-Type: application/json
Authorization: Bearer {{token}}

{
      "name": "federa",
      "date": "2024-01-01",
      "location": "betel",
      "eventType": "gender_specific",
      "maxClientMale": "13" ,
      "maxClientFemale": "3",
      "maxStaffMale": "3",
      "maxStaffFemale": "3",
      "maxGeneralSpots": "300",
      "startDate": "2024-08-01T00:00:00Z",
      "endDate": "2024-08-15T23:59:59Z"
}

###
# @name listEvents
GET {{base_url}}/events
Content-Type: application/json
Authorization: Bearer {{token}}

###
# @name getEvent
GET {{base_url}}/events/{{eventId}}
Content-Type: application/json
Authorization: Bearer {{token}}

###
# @name updateEvent
PUT {{base_url}}/events/{{eventId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "federa1"
}

###
# @name deleteEvent
DELETE {{base_url}}/events/{{eventId}}
Content-Type: application/json
Authorization: Bearer {{token}}


###
# @name excel
GET {{base_url}}/events/{{eventId}}/excel
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
Authorization: Bearer {{token}}