### Base URL
@base_url=http://localhost:3000
@eventId=federa2025
@email=test@test.com
@token=" "

###
# @name createEvent
POST {{base_url}}/events
Content-Type: application/json
Authorization: Bearer 

{
      "name": "federa2025",
      "date": "2024-09-21",
      "location": "ipb central de passos",
      "eventType": "general",
      "maxClientMale": "0" ,
      "maxClientFemale": "0",
      "maxStaffMale": "0",
      "maxStaffFemale": "0",
      "maxGeneralSpots": "200",
      "startDate": "2024-08-19T00:00:00Z",
      "endDate": "2024-09-21T23:59:59Z",
      "price": 5000
}

###
# @name listEvents
GET {{base_url}}/events
Content-Type: application/json
Authorization: Bearer  

###
# @name getEvent
GET {{base_url}}/events/{{eventId}}
Content-Type: application/json
Authorization: Bearer  

###
# @name updateEvent
PUT {{base_url}}/events/{{eventId}}
Content-Type: application/json
Authorization: Bearer  

{
    "name": "federa1"
}

###
# @name deleteEvent
DELETE {{base_url}}/events/{{eventId}}
Content-Type: application/json
Authorization: Bearer 
