### Base URL
@base_url=http://localhost:3000
@commentsId=federa2025
@email=test@test.com
@token=" "

###
# @name createComments
POST {{base_url}}/comments
Content-Type: application/json
Authorization: Bearer  

{
    "comment": "bora!"
}

###
@commentId = {{ createComments.response.body.id }}

###
# @name listCommentss
GET {{base_url}}/comments
Content-Type: application/json

###
# @name getComments
GET {{base_url}}/comments/{{commentId}}
Content-Type: application/json
Authorization: Bearer  

###
# @name updateComments
PATCH {{base_url}}/comments/{{commentId}}
Content-Type: application/json
Authorization: Bearer  

{
    "comment": "string",
    "hide": true
}

###
# @name deleteComments
DELETE {{base_url}}/comments/{{commentId}}
Content-Type: application/json
Authorization: Bearer  