### Base URL
@base_url=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvc3R1bWVyQGNvc3R1bWVyLmJyIiwiaWF0IjoxNzIzNTUxNjExLCJleHAiOjE3MjM1NTUyMTF9._MbgnuFLKpFDfgHtJt1FxjTK3ZDeKZ5RYmfJ9zcBpoY

@commentsId=federa
@email=test@test.com

###
# @name createComments
POST {{base_url}}/comments
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "comment": "string"
}

###
@commentId = {{ createComments.response.body.id }}

###
# @name listCommentss
GET {{base_url}}/comments
Content-Type: application/json

###
# @name getComments
GET {{base_url}}/comments/{{commentId}}
Content-Type: application/json
Authorization: Bearer {{token}}

###
# @name updateComments
PATCH {{base_url}}/comments/{{commentId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "comment": "string",
    "hide": true
}

###
# @name deleteComments
DELETE {{base_url}}/comments/{{commentId}}
Content-Type: application/json
Authorization: Bearer {{token}}