### Base URL
@base_url=http://localhost:3000
@eventId=federa1

### Verificar Status de Inscrição para um Evento
# @name time
GET {{base_url}}/events/{{eventId}}/event-status
Content-Type: application/json
