### Base URL
@base_url=https://us-central1-federa-api.cloudfunctions.net/api
@eventId=federa

### Verificar Status de Inscrição para um Evento
# @name time
GET {{base_url}}/events/{{eventId}}/event-status
Content-Type: application/json
