### Base URL
@base_url=http://localhost:3000
@email=test1@test.com
@eventId=federa1
@token="${env:TOKEN}"

###
# @name makeReservation
POST {{base_url}}/events/{{eventId}}/reserve-spot
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ticket_kind": "full",
  "userType": "client"
}

### Get reservations for a specific user
# @name getReservationByUser
GET {{base_url}}/users/reservations
Content-Type: application/json
Authorization: Bearer {{token}}

### Get reservations for a specific user
# @name cancelledReservationByUser
PATCH {{base_url}}/users/cancel-reservation
Content-Type: application/json
Authorization: Bearer {{token}}

### Get reservations for a specific event
# @name getReservationByEvents
GET {{base_url}}/events/{{eventId}}/reservations
Content-Type: application/json
Authorization: Bearer {{token}}