### Base URL
@base_url=http://localhost:3000
@email = test@test.com
@eventId=federa2025
@token=" "

###
# @name createStaffPass
POST {{base_url}}/staffpass/{{eventId}}
Content-Type: application/json
Authorization: Bearer  

{
    "staff_pass": "yourStaffPas2s"
}

###
# @name getStaffPass
POST {{base_url}}/staffpass/{{eventId}}/is-staff
Content-Type: application/json
Authorization: Bearer  

{
    "staff_pass": "yourStaffPas2s"
}

###
# @name updateStaffPass
PATCH {{base_url}}/staffpass/{{eventId}}
Content-Type: application/json
Authorization: Bearer  

{
    "staff_pass": "newStaffPass"
}

###
# @name deleteStaffPass
DELETE {{base_url}}/staffpass/{{eventId}}
Content-Type: application/json
Authorization: Bearer 
