### Base URL
@base_url=https://us-central1-federa-api.cloudfunctions.net/api
@email = test@test.com
@eventId=federa
@token=

###
# @name createStaffPass
POST {{base_url}}/staffpass/{{eventId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "staff_pass": "yourStaffPas2s"
}

###
# @name getStaffPass
POST {{base_url}}/staffpass/{{eventId}}/is-staff
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "staff_pass": "yourStaffPas2s"
}

###
# @name updateStaffPass
PATCH {{base_url}}/staffpass/{{eventId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "staff_pass": "newStaffPass"
}

###
# @name deleteStaffPass
DELETE {{base_url}}/staffpass/{{eventId}}
Content-Type: application/json
Authorization: Bearer {{token}}
