### Base URL
@base_url=http://localhost:3000
@eventId=federa1
@email=test@test.com
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvc3R1bWVyQGNvc3R1bWVyLmJyIiwiaWF0IjoxNzIzNTU0NzE3LCJleHAiOjE3MjM1NTgzMTd9.hN5_LApZzuFOlRBhGx53IuQ4F2niWOWJDXoGHhvpqf8

### Get installments
# @name getInstallments
GET {{base_url}}/events/{{eventId}}/installments
Content-Type: application/json
Authorization: Bearer {{token}}