### Base URL
@base_url=http://localhost:3000
@eventId=federa2025
@token=" "

### Get installments
# @name getInstallments
GET {{base_url}}/events/{{eventId}}/installments
Content-Type: application/json
Authorization: Bearer  