### Base URL
@base_url=http://localhost:3000
@email = test@test.com
@eventId=federa1
@token="${env:TOKEN}"

###
# @name waitingList
GET {{base_url}}/events/{{eventId}}/waiting-list
Content-Type: application/json
Authorization: Bearer {{token}}
