### Base URL
@base_url=http://localhost:3000
@email = test@test.com
@eventId=federa1
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvc3R1bWVyQGNvc3R1bWVyLmJyIiwiaWF0IjoxNzIzNTU2NzcyLCJleHAiOjE3MjM1NjAzNzJ9.unBcR5dMcnvj07M7f2qW0ySPSOnculxaQti1euDq4j8


###
# @name waitingList
GET {{base_url}}/events/{{eventId}}/waiting-list
Content-Type: application/json
Authorization: Bearer {{token}}