### Base URL
@base_url=https://us-central1-federa-api.cloudfunctions.net/api
@email = test@test.com
@eventId=federa
@token=

###
# @name waitingList
GET {{base_url}}/events/{{eventId}}/waiting-list
Content-Type: application/json
Authorization: Bearer {{token}}
